#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# for the 9th iteration, displays Best School and then Hi

c=0
while [ "$c" -lt "10" ]
do
    echo "Best School"

    if [ "$c" -eq "8" ]
    then
        echo "Hi"
    fi

    c=$(( c + 1 ))
done
